workflows:
  react-native-android:
    name: React Native Android
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      vars:
        PACKAGE_NAME: "com.taxidodriver"  # Replace with your app's package name
      android_signing:
        - keystore_reference: "codemagic_keystore"  # Reference to your uploaded keystore
    scripts:
      - name: Set Android SDK location
        script: echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      - name: Install npm dependencies
        script: npm install
      - name: Build Android release
        script: |
          cd android
          UPDATED_BUILD_NUMBER=$(google-play get-latest-build-number --track internal --package-name $PACKAGE_NAME)
          ./gradlew bundleRelease -PversionCode=$UPDATED_BUILD_NUMBER -PversionName=1.0.$UPDATED_BUILD_NUMBER
    artifacts:
      - android/app/build/outputs/**/*.aab
    publishing:
      email:
        recipients:
          - your_email@example.com  # Replace with your email for notifications
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS  # Set in Codemagic secrets
        track: internal
        submit_as_draft: true
